# Generated by Django 5.0.1 on 2024-01-12 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userprofile_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="subscribers",
            new_name="subscribers_to",
        ),
    ]
